name: travelplates
description: "An app to keep track of state plates on long trips"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.4.0
  path_provider: ^2.1.3
  intl: ^0.18.1
  geolocator: ^12.0.0
  flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon" # Or true for default name
  ios: true                # Or true for default name
  image_path: "assets/icon/app_icon3.png" # Path to your icon image